In [2]:
from alpha_vantage.timeseries import TimeSeries

In [3]:
API_key = "******"

In [4]:
ts=TimeSeries(key=API_key,output_format='pandas')

In [5]:
data=ts.get_daily("AAPL")

In [6]:
data

(            1. open   2. high    3. low  4. close   5. volume
 date
 2026-01-28  257.650  258.8550  254.5100    256.44  41287971.0
 2026-01-27  259.170  261.9500  258.2100    258.27  48787855.0
 2026-01-26  251.480  256.5600  249.8000    255.41  55969234.0
 2026-01-23  247.320  249.4100  244.6800    248.04  41688982.0
 2026-01-22  249.200  251.0000  248.1500    248.35  39708340.0
 ...             ...       ...       ...       ...         ...
 2025-09-11  226.875  230.4500  226.6500    230.03  50208578.0
 2025-09-10  232.185  232.4200  225.9500    226.79  83440810.0
 2025-09-09  237.000  238.7805  233.3600    234.35  66313918.0
 2025-09-08  239.300  240.1500  236.3400    237.88  48999495.0
 2025-09-05  239.995  241.3200  238.4901    239.69  54870397.0

 [100 rows x 5 columns],
 {'1. Information': 'Daily Prices (open, high, low, close) and Volumes',
  '2. Symbol': 'AAPL',
  '3. Last Refreshed': '2026-01-28',
  '4. Output Size': 'Compact',
  '5. Time Zone': 'US/Eastern'})

In [7]:
data[0]

            1. open   2. high    3. low  4. close   5. volume
date
2026-01-28  257.650  258.8550  254.5100    256.44  41287971.0
2026-01-27  259.170  261.9500  258.2100    258.27  48787855.0
2026-01-26  251.480  256.5600  249.8000    255.41  55969234.0
2026-01-23  247.320  249.4100  244.6800    248.04  41688982.0
2026-01-22  249.200  251.0000  248.1500    248.35  39708340.0
...             ...       ...       ...       ...         ...
2025-09-11  226.875  230.4500  226.6500    230.03  50208578.0
2025-09-10  232.185  232.4200  225.9500    226.79  83440810.0
2025-09-09  237.000  238.7805  233.3600    234.35  66313918.0
2025-09-08  239.300  240.1500  236.3400    237.88  48999495.0
2025-09-05  239.995  241.3200  238.4901    239.69  54870397.0

[100 rows x 5 columns]

In [8]:
data2=data[0]

In [10]:
data2.columns

Index(['1. open', '2. high', '3. low', '4. close', '5. volume'], dtype='object')

In [11]:
data2["4. close"].to_frame()

            4. close
date
2026-01-28    256.44
2026-01-27    258.27
2026-01-26    255.41
2026-01-23    248.04
2026-01-22    248.35
...              ...
2025-09-11    230.03
2025-09-10    226.79
2025-09-09    234.35
2025-09-08    237.88
2025-09-05    239.69

[100 rows x 1 columns]